import type { AssetKind } from './assets';
import type { PublicAsset } from './media';

/**
 * Shipped website key art, by event slug.
 *
 * The same arrangement the seasonal theme uses: the repository ships artwork,
 * the admin can upload their own into the same slot, and an upload always wins.
 * A slug with no entry simply has no default, which is a perfectly normal state
 * — the event then shows its official flyer, which is the point.
 *
 * These files are SECONDARY art. They are backgrounds the site composes around
 * an event; they are never that event's flyer and never replace one.
 * Generated by `npx tsx scripts/generate-event-art.ts`.
 */

const DIR = '/events';

/** Slugs that ship with a background. Everything else falls back to the flyer. */
const SLUGS = [
  'scream-paint-sip',
  'snoopy-paint-sip-night',
  'junior-h-paint-sip',
  'oasis-fridays',
  'oasis-latin-saturdays',
] as const;

const SPARES = ['generic-nightlife', 'generic-celebration', 'generic-comedy'] as const;

/** Every shipped file, for the asset check and the docs. */
export const EVENT_ART_FILES: string[] = [...SLUGS, ...SPARES].flatMap((slug) => [
  `${DIR}/${slug}.webp`,
  `${DIR}/${slug}-tall.webp`,
]);

function asset(path: string, width: number, height: number, ratio: string): PublicAsset {
  return {
    path,
    kind: 'image' as AssetKind,
    // Decorative by definition: everything it conveys — the event's name, date,
    // price and status — is rendered beside it as real text.
    alt: null,
    width,
    height,
    ratio,
    focal: '50% 45%',
    status: 'final',
  };
}

export interface DefaultEventArt {
  wide: PublicAsset;
  tall: PublicAsset;
}

const DEFAULTS: Record<string, DefaultEventArt> = Object.fromEntries(
  [...SLUGS, ...SPARES].map((slug) => [
    slug,
    {
      wide: asset(`${DIR}/${slug}.webp`, 1600, 900, '16:9'),
      tall: asset(`${DIR}/${slug}-tall.webp`, 900, 1125, '4:5'),
    },
  ]),
);

/** The shipped art for an event, or null when it has none. */
export function defaultEventArt(slug: string | null): DefaultEventArt | null {
  if (!slug) return null;
  return DEFAULTS[slug] ?? null;
}
